#!/usr/bin/env python3
"""
Generate 100 Qualified Leads (20 per industry) - FIXED VERSION
✅ No duplicates
✅ All mandatory fields included
"""
import asyncio
import subprocess
import sys
from pathlib import Path

INDUSTRIES = [
    'manufacturing',
    'wholesale',
    'equipment_rental',
    'printing',
    'professional_services'
]

# Target more than 20 to account for low qualification rates
TARGET_PER_INDUSTRY = 100

async def main():
    """Generate 20 leads per industry (100 total)."""
    print("="*80)
    print("🚀 GENERATING 100 QUALIFIED LEADS - FIXED VERSION")
    print("="*80)
    print("Target: 20 qualified leads per industry (100 total)")
    print("Industries: 5 (manufacturing, wholesale, equipment_rental, printing, professional_services)")
    print("\nFixes Applied:")
    print("  ✅ Deduplication across queries (no duplicate businesses)")
    print("  ✅ All mandatory fields included (revenue, employees, SDE, confidence)")
    print("  ✅ Pre-qualification before enrichment (saves API costs)")
    print("="*80 + "\n")

    script_dir = Path(__file__).parent
    phase2_script = script_dir / 'generate_leads_phase2_fixed.py'

    all_results = {}

    for idx, industry in enumerate(INDUSTRIES, 1):
        print(f"\n{'='*80}")
        print(f"📋 INDUSTRY {idx}/5: {industry.upper()}")
        print(f"{'='*80}\n")

        # Run the Phase 2 script for this industry
        result = subprocess.run(
            [
                sys.executable,
                str(phase2_script),
                '--target', str(TARGET_PER_INDUSTRY),
                '--industry', industry
            ],
            capture_output=False,
            text=True
        )

        if result.returncode != 0:
            print(f"❌ Error generating leads for {industry}")
            all_results[industry] = 0
        else:
            # Count the leads generated
            output_dir = script_dir.parent / 'data' / 'outputs'
            latest_file = max(
                output_dir.glob(f'PHASE2_FIXED_LEADS_{industry}_*.csv'),
                key=lambda p: p.stat().st_mtime,
                default=None
            )
            if latest_file:
                with open(latest_file, 'r') as f:
                    lead_count = sum(1 for _ in f) - 1  # Subtract header
                all_results[industry] = lead_count
                print(f"\n✅ Generated {lead_count} qualified leads for {industry}")
            else:
                all_results[industry] = 0

        print(f"\n{'='*80}\n")

    # Final Summary
    print("\n" + "="*80)
    print("🎯 FINAL RESULTS - 100 LEADS GENERATION (FIXED)")
    print("="*80)
    print("\nLeads Generated by Industry:")
    total = 0
    for industry in INDUSTRIES:
        count = all_results.get(industry, 0)
        total += count
        status = "✅" if count >= 15 else "⚠️"
        print(f"  {status} {industry.ljust(25)}: {count:2d} leads")

    print(f"\n  {'TOTAL'.ljust(25)}: {total:2d} leads")
    print("="*80)

    if total >= 80:
        print("\n✅ SUCCESS: Generated sufficient qualified leads!")
    else:
        print(f"\n⚠️  WARNING: Only generated {total} leads (target was 100)")

    print("\n💡 Next Steps:")
    print("   1. Review the generated CSV files in data/outputs/")
    print("   2. Verify all mandatory fields are present")
    print("   3. Check for any duplicate businesses")
    print("   4. Begin outreach with HIGH priority leads")
    print("="*80 + "\n")


if __name__ == '__main__':
    asyncio.run(main())
